spring:
  profiles:
    active: dev, base-addi


security:
  oauth2:
    client:
      registration:
        kakao:
          clientId:
          scope: profile_nickname, profile_image, account_email
          client-name: Kakao
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8010/login/oauth2/code/kakao
          client-authentication-method: POST
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

thymeleaf:
  cache: false
  prefix: file:src/main/resources/templates/